#!/usr/bin/env bash

docker run -dit --name text-generation-webui -p 221:22 -p 7861:7860 --hostname textgen-container --runtime=nvidia --gpus all --shm-size="12gb" --restart unless-stopped textgen-container:latest
